# Falcon-40B T3000 CI end-to-end tests.
# Referenced by: t3k_unit_tests, t3k_demo_tests.

load("//bazel:pytest.bzl", "pytest_suite")

pytest_suite(
    name = "falcon40b_ci_tests",
    srcs = glob(["test_*.py"]),
    deps = [
        "//models/common:utility_functions",
        "//ttnn/ttnn:ttnn_py",
        "@pip//loguru",
        "@pip//torch",
        "@pip//transformers",
    ],
    markers = ["slow"],
    tags = ["ttnn", "nightly", "models", "t3000", "requires_wormhole_b0", "requires_T3000"],
)
