load("//ttnn/bazel:ttnn_operation.bzl", "ttnn_operation")

ttnn_operation(
    name = "isin",
    srcs = [
        "device/isin_device_operation.cpp",
        "device/isin_program_factory.cpp",
        "isin.cpp",
    ],
    hdrs = glob(
        ["**/*.hpp", "**/*.h"],
        exclude = ["device/kernels/**"],
        allow_empty = True,
    ),
    extra_deps = [
        "//ttnn/cpp/ttnn/operations/core:core_hdrs",
    ],
)
