load("//ttnn/bazel:ttnn_operation.bzl", "ttnn_operation")

ttnn_operation(
    name = "kv_cache",
    srcs = [
        "device/fill_cache_multi_core_program_factory.cpp",
        "device/update_cache_device_operation.cpp",
        "device/update_cache_multi_core_program_factory.cpp",
        "kv_cache.cpp",
    ],
    hdrs = glob(
        ["**/*.hpp", "**/*.h"],
        exclude = ["device/kernels/**"],
        allow_empty = True,
    ),
    extra_hdrs_deps = [
        "//ttnn/cpp/ttnn/operations/core:core_hdrs",
    ],
    extra_deps = [
        "//ttnn/cpp/ttnn/operations/core:core_hdrs",
    ],
)
