#!/bin/bash
# Verifies that Bazel-generated linker scripts match CMake-generated ones.
#
# This compares the preprocessed .ld files from Bazel against the reference
# copies in runtime/hw/toolchain/ that were generated by CMake.
#
# Usage: run via `bazel test //tt_metal/hw/toolchain:verify_linker_scripts`
#        or standalone: ./verify_linker_scripts_test.sh <bazel_output_dir> <cmake_reference_dir>

set -euo pipefail

BAZEL_DIR="${1:?Usage: $0 <bazel_output_dir> <cmake_reference_dir>}"
CMAKE_DIR="${2:?Usage: $0 <bazel_output_dir> <cmake_reference_dir>}"

# Map from Bazel output filenames to CMake output paths.
# Bazel produces flat files; CMake puts them under arch-specific subdirs.
fail_count=0
pass_count=0

compare() {
    local bazel_file="$1"
    local cmake_file="$2"
    local label="$3"

    if [ ! -f "$cmake_file" ]; then
        echo "SKIP: $label (no CMake reference at $cmake_file)"
        return
    fi
    if [ ! -f "$bazel_file" ]; then
        echo "FAIL: $label (Bazel output missing: $bazel_file)"
        fail_count=$((fail_count + 1))
        return
    fi
    if diff -q "$bazel_file" "$cmake_file" > /dev/null 2>&1; then
        echo "OK:   $label"
        pass_count=$((pass_count + 1))
    else
        echo "FAIL: $label"
        diff -u "$cmake_file" "$bazel_file" | head -20
        fail_count=$((fail_count + 1))
    fi
}

# Old-style main.ld scripts
PROCS="brisc ncrisc ierisc subordinate_ierisc trisc0 trisc1 trisc2 aerisc main_aerisc subordinate_aerisc"
TYPES="firmware kernel"
for arch in wormhole blackhole; do
    for proc in $PROCS; do
        for type in $TYPES; do
            compare \
                "$BAZEL_DIR/${type}_${proc}.ld" \
                "$CMAKE_DIR/$arch/${type}_${proc}.ld" \
                "$arch/${type}_${proc}.ld"
        done
    done
done

# Erisc-b0 scripts (wormhole only)
for script in erisc-b0-kernel erisc-b0-kernel_iram erisc-b0-app erisc-b0-app_iram; do
    compare \
        "$BAZEL_DIR/${script}.ld" \
        "$CMAKE_DIR/wormhole/${script}.ld" \
        "wormhole/${script}.ld"
done

# TLS-style scripts (quasar)
for script in firmware_trisc kernel_trisc kernel_trisc_lgc firmware_dm kernel_dm kernel_dm_lgc; do
    compare \
        "$BAZEL_DIR/${script}.ld" \
        "$CMAKE_DIR/quasar/${script}.ld" \
        "quasar/${script}.ld"
done

echo ""
echo "Results: $pass_count passed, $fail_count failed"

if [ "$fail_count" -gt 0 ]; then
    exit 1
fi
