# TTNN benchmark unit test.

load("//bazel:pytest.bzl", "pytest_suite")

pytest_suite(
    name = "benchmark_tests",
    srcs = glob(["test_*.py"]),
    deps = [
        "//ttnn/ttnn:ttnn_py",
        "@pip//torch",
    ],
    markers = ["post_commit", "models_performance_bare_metal"],
    tags = ["ttnn", "unit", "benchmark", "requires_wormhole_b0", "requires_blackhole", "ttsim"],
)
