load("//ttnn/bazel:ttnn_operation.bzl", "ttnn_operation")

ttnn_operation(
    name = "dropout",
    srcs = [
        "device/dropout_device_operation.cpp",
        "device/dropout_program_factory.cpp",
        "dropout.cpp",
    ],
    hdrs = glob(
        ["**/*.hpp", "**/*.h"],
        exclude = ["device/kernels/**"],
        allow_empty = True,
    ),
)
