load("//ttnn/bazel:ttnn_operation.bzl", "ttnn_operation")

ttnn_operation(
    name = "pool",
    srcs = [
        "generic/device/pool_multi_core_program_factory.cpp",
        "generic/device/pool_op.cpp",
        "generic/generic_pools.cpp",
        "global_avg_pool/global_avg_pool.cpp",
        "grid_sample/device/grid_sample_bilinear_program_factory.cpp",
        "grid_sample/device/grid_sample_device_operation.cpp",
        "grid_sample/device/grid_sample_nearest_program_factory.cpp",
        "grid_sample/device/grid_sample_utils.cpp",
        "grid_sample/grid_sample.cpp",
        "grid_sample/grid_sample_prepare_grid.cpp",
        "pool_utils.cpp",
        "rotate/device/rotate_bilinear_program_factory.cpp",
        "rotate/device/rotate_device_operation.cpp",
        "rotate/device/rotate_nearest_program_factory.cpp",
        "rotate/rotate.cpp",
        "upsample/device/upsample_bilinear_program_factory_multicore.cpp",
        "upsample/device/upsample_common.cpp",
        "upsample/device/upsample_device_operation.cpp",
        "upsample/device/upsample_nearest_float_program_factory.cpp",
        "upsample/device/upsample_program_factory_multicore_interleaved.cpp",
        "upsample/device/upsample_program_factory_multicore_sharded.cpp",
        "upsample/upsample.cpp",
    ],
    hdrs = glob(["**/*.hpp", "**/*.h"], allow_empty = True),
    kernel_hdrs = glob(
        [
            "device/kernels/**",
            "generic/device/kernels/**",
            "grid_sample/device/kernels/**",
            "rotate/device/kernels/**",
            "upsample/device/kernels/**",
        ],
        exclude = ["**/*.hpp", "**/*.h"],
        allow_empty = True,
    ),
    extra_hdrs_deps = [
        "//ttnn/cpp/ttnn/operations/core:core_hdrs",
        "//ttnn/cpp/ttnn/operations/sliding_window:sliding_window_hdrs",
    ],
    extra_deps = [
        "//ttnn/cpp/ttnn/operations/conv:conv_hdrs",
        "//ttnn/cpp/ttnn/operations/core:core_hdrs",
        "//ttnn/cpp/ttnn/operations/data_movement:data_movement_hdrs",
        "//ttnn/cpp/ttnn/operations/experimental/reshape:reshape_hdrs",
        "//ttnn/cpp/ttnn/operations/reduction:reduction_hdrs",
        "//ttnn/cpp/ttnn/operations/sliding_window:sliding_window_hdrs",
    ],
)
