load("//ttnn/bazel:ttnn_operation.bzl", "ttnn_operation")

ttnn_operation(
    name = "full_like",
    srcs = [
        "full_like.cpp",
    ],
    hdrs = glob(
        ["**/*.hpp", "**/*.h"],
        exclude = ["device/kernels/**"],
        allow_empty = True,
    ),
    extra_deps = [
        "//ttnn/cpp/ttnn/operations/full:full_hdrs",
    ],
)
