load("//ttnn/bazel:ttnn_operation.bzl", "ttnn_operation")

ttnn_operation(
    name = "bcast_to",
    srcs = [
        "bcast_to.cpp",
        "device/bcast_to_device_operation.cpp",
        "device/bcast_to_program_factory.cpp",
        "device/bcast_to_utils.cpp",
    ],
    hdrs = glob(
        ["**/*.hpp", "**/*.h"],
        exclude = ["device/kernels/**"],
        allow_empty = True,
    ),
    extra_deps = [
        "//ttnn/cpp/ttnn/operations/core:core_hdrs",
    ],
)
