load("//ttnn/bazel:ttnn_operation.bzl", "ttnn_operation")

ttnn_operation(
    name = "full",
    srcs = [
        "device/full_device_operation.cpp",
        "device/full_program_factory_interleaved.cpp",
        "device/full_program_factory_nd_sharded.cpp",
        "device/full_program_factory_sharded.cpp",
        "full.cpp",
    ],
    hdrs = glob(
        ["**/*.hpp", "**/*.h"],
        exclude = ["device/kernels/**"],
        allow_empty = True,
    ),
    extra_deps = [
        "//ttnn/cpp/ttnn/operations/moreh:moreh_hdrs",
    ],
)
