load("//ttnn/bazel:ttnn_operation.bzl", "ttnn_operation")

ttnn_operation(
    name = "quantization",
    srcs = [
        "quantization.cpp",
    ],
    hdrs = glob(
        ["**/*.hpp", "**/*.h"],
        exclude = ["device/kernels/**"],
        allow_empty = True,
    ),
    extra_deps = [
        "//ttnn/cpp/ttnn/operations/data_movement:data_movement_hdrs",
        "//ttnn/cpp/ttnn/operations/eltwise/binary:binary_hdrs",
        "//ttnn/cpp/ttnn/operations/eltwise/binary_ng:binary_ng_hdrs",
        "//ttnn/cpp/ttnn/operations/eltwise/unary:unary_hdrs",
    ],
)
