# 4x Blackhole quiet-box sanity test.

load("//bazel:pytest.bzl", "pytest_suite")

pytest_suite(
    name = "bh_quietbox_tests",
    srcs = glob(["test_*.py"]),
    deps = [
        "//tests/ttnn:test_utils",
        "//ttnn/ttnn:ttnn_py",
        "@pip//torch",
    ],
    tags = ["scale_out", "blackhole"],
)
