# Common model utilities shared across test files.

load("@rules_python//python:py_library.bzl", "py_library")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "utility_functions",
    testonly = True,
    srcs = ["utility_functions.py"],
    deps = [
        "//ttnn/ttnn:ttnn_py",
        "@pip//numpy",
        "@pip//torch",
        "@pip//loguru",
        "@pip//pytest",
    ],
)
