# Experimental model tests.

load("//bazel:pytest.bzl", "pytest_suite")

pytest_suite(
    name = "bloom_tests",
    srcs = glob(["test_*.py"]),
    deps = [
        "//models/common:utility_functions",
        "//ttnn/ttnn:ttnn_py",
        "@pip//loguru",
        "@pip//torch",
        "@pip//transformers",
        "//tests/tt_eager:sweep_test_utils",
    ],
    markers = ["slow"],
    tags = ["ttnn", "nightly", "models", "requires_wormhole_b0"],
)
