load("//ttnn/bazel:ttnn_operation.bzl", "ttnn_operation")

ttnn_operation(
    name = "copy",
    srcs = [
        "typecast/device/typecast_device_op.cpp",
        "typecast/device/typecast_program_factory.cpp",
        "typecast/device/typecast_rm_chunked_program_factory.cpp",
        "typecast/device/typecast_sharded_program_factory.cpp",
        "typecast/typecast.cpp",
    ],
    hdrs = glob(
        ["**/*.hpp", "**/*.h"],
        exclude = ["device/kernels/**"],
        allow_empty = True,
    ),
    extra_deps = [
        "//ttnn/cpp/ttnn/operations/core:core_hdrs",
    ],
)
