load("//ttnn/bazel:ttnn_operation.bzl", "ttnn_operation")

ttnn_operation(
    name = "where",
    srcs = [
        "device/program_factory/element_wise_multi_core_where_program.cpp",
        "device/where_device_operation.cpp",
        "where.cpp",
    ],
    hdrs = glob(
        ["**/*.hpp", "**/*.h"],
        exclude = ["device/kernels/**"],
        allow_empty = True,
    ),
    extra_hdrs_deps = [
        "//ttnn/cpp/ttnn/operations/core:core_hdrs",
    ],
)
