load("//ttnn/bazel:ttnn_operation.bzl", "ttnn_operation")

ttnn_operation(
    name = "bernoulli",
    srcs = [
        "bernoulli.cpp",
        "device/bernoulli_device_operation.cpp",
        "device/bernoulli_program_factory.cpp",
    ],
    hdrs = [
        "bernoulli.hpp",
        "device/bernoulli_device_operation.hpp",
    ],
    # kernel_hdrs auto-globs device/kernels/**
)
