# Nightly EfficientDet-D0 model test.

load("//bazel:pytest.bzl", "pytest_suite")

pytest_suite(
    name = "efficientdetd0_tests",
    srcs = glob(["test_*.py"]),
    deps = [
        "//ttnn/ttnn:ttnn_py",
        "@pip//torch",
    ],
    markers = ["slow"],
    tags = ["ttnn", "nightly", "models", "single_card", "requires_wormhole_b0"],
)
