# Device performance matmul stagger test.

load("//bazel:pytest.bzl", "pytest_suite")

pytest_suite(
    name = "matmul_stagger_tests",
    srcs = glob(["test_*.py"]),
    deps = [
        "//ttnn/ttnn:ttnn_py",
        "@pip//torch",
    ],
    markers = ["models_device_performance_bare_metal"],
    tags = ["perf", "matmul_stagger", "requires_wormhole_b0"],
)
