exports_files(
    ["dev_mem_map.h"],
    visibility = ["//tt_metal/hw/toolchain:__pkg__"],
)

headers = glob(["**/*.h", "**/*.hpp"])

filegroup(
    name = "all_headers",
    srcs = headers,
    visibility = ["//visibility:public"],
)

cc_library(
    name = "rv-qa-hdrs",
    hdrs = headers,
    includes = ["."],
    visibility = ["//visibility:public"],
)
