# Test script utilities imported by conftest.py and test files.

load("@rules_python//python:py_library.bzl", "py_library")

package(default_visibility = ["//tests:__subpackages__"])

py_library(
    name = "common",
    testonly = True,
    srcs = [
        "__init__.py",
        "common.py",
    ],
    deps = [
        "@pip//loguru",
    ],
    visibility = ["//visibility:public"],
)
